#!/usr/bin/env python3
"""
Wyze 모델용 '랜덤 입력' 생성기 — challenge 와 동일 포맷
=================================================================

목적
----
generate_challenge_wyze_uniform.py 가 만드는 challenge_NNN.{bin,json} 과
완전히 동일한 형식으로, 다만 최적화를 **거치지 않은** 순수 랜덤 이미지를
N장 dump 한다.

WideResNet 참조 실험 CSV (origin_flipped_topk_with_bitflips_wideresnet_quan.csv)
의 random_top* / random_flipped_top* 컬럼을 Wyze 실험에서도 채울 수
있게 하는 baseline 입력셋이다.

차이점 (challenge vs random)
----------------------------
* challenge : 특정 ROI 의 5-class softmax 가 균등해지도록 raw 를 **최적화**
* random    : init_raw() 가 만든 raw 를 **최적화 없이 그대로** 사용

따라서 random_NNNN.json 은
  - challenge 전용 필드(target_*, uniform_gap, converged 등)는 null
  - 동일 ROI set 의 rois_logits / rois_topk 는 그대로 채움 (verifier 호환)

사용
----
  python generate_random_inputs.py                    # N=1000, seed=12345
  python generate_random_inputs.py --num 100          # 100장
  python generate_random_inputs.py --out data/challenge/wyze_random_v2
  python generate_random_inputs.py --fingerprint path/to/fingerprint_rois.json
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import torch

SCRIPT_DIR = Path(__file__).resolve().parent          # = AI-Attestation/
WYZE_DIR   = SCRIPT_DIR / "wyze_model"
sys.path.insert(0, str(WYZE_DIR))
sys.path.insert(0, str(SCRIPT_DIR))

# Wyze 모델 (challenge 생성과 동일 경로)
from classify import load_model, load_input, CLASS_NAMES  # noqa: E402

# ROI 선정 / 입력 초기화 / bin 저장 유틸은 challenge 생성기와 공용
from generate_challenge_wyze import (                       # noqa: E402
    extract_roi_logits,
    extract_roi_topk,
    init_raw,
    save_raw_bin,
    select_golden_rois,
)


DEVICE = torch.device("cpu")

# challenge 와 같은 K=16 ROI 사용 (BAIV-style top-K 검증과 호환)
K_GOLDEN = 16

# 기본 저장 위치: challenge 의 wyze_ste_uniform 과 평행한 위치
DEFAULT_SAVE_DIR = SCRIPT_DIR / "data" / "challenge" / "wyze_random"

# challenge 생성 때 만들어둔 fingerprint 가 있으면 그대로 재사용해
# verifier 코드 경로가 challenge 와 100% 동일하게 흐르도록 한다.
DEFAULT_FINGERPRINT = (
    SCRIPT_DIR / "data" / "challenge" / "wyze_ste_uniform" / "fingerprint_rois.json"
)


# ────────────────────────────────────────────────────────────────────────────
def resolve_rois(model, fingerprint_path: Path, save_dir: Path):
    """ROI 정의 확보. 우선순위:

      1) --fingerprint 로 지정된 경로 / 기본 challenge fingerprint 가 있으면 로드
      2) 없으면 select_golden_rois 로 즉석 생성 + save_dir 에 사본 저장
    """
    if fingerprint_path.exists():
        with open(fingerprint_path, encoding="utf-8") as f:
            fp = json.load(f)
        print(f"[ROI] loaded {len(fp['rois'])} ROIs from {fingerprint_path}")
        return fp

    print(f"[ROI] {fingerprint_path} 없음 → select_golden_rois 로 새로 생성")
    rois = select_golden_rois(model, K=K_GOLDEN)
    fp = {
        "K": K_GOLDEN,
        "mode": "random_inputs",
        "rois": rois,
        "class_names": CLASS_NAMES,
        "note": "auto-generated by generate_random_inputs.py (fingerprint 없을 때)",
    }
    return fp


def make_one(model, rois, bin_path: Path, json_path: Path, idx: int):
    """랜덤 raw 한 장 → bin 저장 → 재로딩 후 forward → json 저장.

    재로딩-후-forward 방식을 쓰는 이유:
      verifier 가 .bin 을 다시 읽어 검증할 때와 정확히 동일한 경로를 거치게
      해야 rois_logits 값이 round-trip safe.
    """
    raw = init_raw()                # (1, 3, 360, 640) float [0,255]
    save_raw_bin(raw, bin_path)     # 640x360x3 uint8 로 저장

    x_int8, _ = load_input(str(bin_path), preprocessed=False)
    with torch.no_grad():
        d32, d16 = model(x_int8.squeeze(0))

    logits = extract_roi_logits(d32, d16, rois)
    topk   = extract_roi_topk(d32, d16, rois)

    payload = {
        "challenge_idx": idx,
        "mode": "random",
        # challenge 전용 필드: 의미 없음 → null (verifier 가 무시할 수 있게 키 보존)
        "converged": None,
        "target_roi_idx": None,
        "target_roi_cell": None,
        "uniform_gap": None,
        "obj_sigmoid_at_target": None,
        "observed_softmax_at_target": None,
        "iters_to_best": 0,
        # 핵심: challenge 와 동일 ROI 에서의 logit/topk
        "rois_logits": logits,
        "rois_topk":   topk,
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def main():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--num",  type=int, default=1000,
                   help="생성할 랜덤 이미지 수 (default 1000)")
    p.add_argument("--out",  type=str, default=str(DEFAULT_SAVE_DIR),
                   help=f"출력 디렉터리 (default {DEFAULT_SAVE_DIR})")
    p.add_argument("--seed", type=int, default=12345,
                   help="RNG seed (default 12345). 같은 seed → 같은 입력셋.")
    p.add_argument("--fingerprint", type=str, default=str(DEFAULT_FINGERPRINT),
                   help=f"ROI 정의 JSON 경로 (default {DEFAULT_FINGERPRINT}). "
                        "없으면 select_golden_rois 로 자동 생성.")
    p.add_argument("--variant", type=str, default="ste",
                   choices=["ste", "numpy", "diff"],
                   help="load_model variant (default 'ste' — challenge 와 동일)")
    args = p.parse_args()

    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"output dir : {out_dir}")
    print(f"target N   : {args.num}")
    print(f"seed       : {args.seed}")
    print(f"variant    : {args.variant}")

    # seed 고정 (init_raw 가 np.random.rand + torch.rand/randn 모두 사용)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    # 모델 로딩
    print(f"loading model ...")
    model, model_type = load_model(args.variant)
    model.to(DEVICE)
    model.eval()
    for prm in model.parameters():
        prm.requires_grad_(False)
    print(f"  model_type={model_type}, classes={CLASS_NAMES}")

    # ROI 정의 확보 (challenge 와 동일 set 우선, 없으면 즉석 생성)
    fp = resolve_rois(model, Path(args.fingerprint), out_dir)
    rois = fp["rois"]

    # 출력 디렉터리에도 fingerprint 사본 저장 — self-contained
    with open(out_dir / "fingerprint_rois.json", "w", encoding="utf-8") as f:
        json.dump(fp, f, indent=2)

    # 메타: 어떤 설정으로 만들었는지
    with open(out_dir / "random_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "kind": "random_inputs",
            "num":  args.num,
            "seed": args.seed,
            "variant": args.variant,
            "fingerprint_src": str(args.fingerprint),
            "raw_resolution": [640, 360, 3],
            "raw_dtype": "uint8",
            "init_raw_distribution":
                "half uniform[0,255), half clipped N(128,30^2) — see init_raw()",
        }, f, indent=2)

    # 이미 있는 파일 건너뛰기 (resume 가능)
    done_ids = set()
    for p_bin in out_dir.glob("random_*.bin"):
        stem = p_bin.stem.split("_", 1)[1]
        if stem.isdigit():
            done_ids.add(int(stem))
    print(f"existing   : {len(done_ids)} bin files in {out_dir.name}/")

    log_every = max(1, args.num // 20)
    new_count = 0
    for i in range(1, args.num + 1):
        if i in done_ids:
            continue
        bin_path  = out_dir / f"random_{i:04d}.bin"
        json_path = out_dir / f"random_{i:04d}.json"
        make_one(model, rois, bin_path, json_path, i)
        new_count += 1
        if new_count % log_every == 0 or i == args.num:
            print(f"  [{i:>5}/{args.num}] saved → {bin_path.name}")

    print(f"\n[done] generated {new_count} new (total target {args.num}) in {out_dir}")


if __name__ == "__main__":
    main()
